# rate limitng zones in shared memory
# zone 1: General API requests -> 10 reqs/s/IP
limit_req_zone $binary_remote_addr zone=api_general_limit:10m rate=10r/s;

# zone 2: sensitive public endpoints reports and simulation -> 2 reqs/s/IP
limit_req_zone $binary_remote_addr zone=api_strict_limit:10m rate=2r/s;

# json payload on 429
error_page 429 = @rate_limit_exceeded;

server {
    listen 80;
    server_name localhost;

    # forwarding headers
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # strict endpoints
    location ~ ^/api/(auth/(login|register|setup-2fa|verify-2fa)|(guests|users)/reported-fires|uploads|simulation) {
        limit_req zone=api_strict_limit burst=5 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # general backend API routes
    location ~ ^/api/(guests|users/reported-fires|ping) {
        limit_req zone=api_general_limit burst=20 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # auth API endpoints
    location /api/ {
        limit_req zone=api_general_limit burst=30 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header connection "";
    }

    # sys health checks
    location = /health {
        limit_req zone=api_general_limit burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
    }

    # swagger documentation
    location ~ ^/(docs|openapi.json|redoc) {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
    }

    # Next.js web frontend + reload
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # rate limiter handler
    location @rate_limit_exceeded {
        default_type application/json;
        return 429 '{"detail": "Requests rate limit exceeded."}';
    }
}