name: Deploy to Staging

on:
    push:
        branches:
            - staging
    pull_request:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Staging
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                command_timeout: 30m
                script: |
                    cd /home/ubuntu/staging
                    git fetch origin staging
                    git reset --hard origin/staging
                    cp /home/ubuntu/app/app/frontend/src/Dockerfile app/frontend/src/Dockerfile
                    cp /home/ubuntu/app/app/frontend/src/package.json app/frontend/src/package.json
                    cp /home/ubuntu/app/app/frontend/src/tsconfig.json app/frontend/src/tsconfig.json
                    cd /home/ubuntu/app/docker-compose.yml docker-compose.yml
                    sed -i 's/- "5432:5432"/- "127.0.0.1:5433:5432"/' docker-compose.yml
                    sed -i 's/- "8000:8000"/- "127.0.0.1:8001:8000"/' docker-compose.yml
                    sed -i 's/- "8080:80"/- "127.0.0.1:8082:80"/' docker-compose.yml

                    docker compose -p staging -f docker-compose.yml -f docker-compose.staging.yml up -d --build
                    docker system prune -f
                
